# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='题目')),
                ('category', models.CharField(choices=[('no-tec', '非技术'), ('tec', '技术')], default='tec', max_length=20, verbose_name='分类')),
                ('limit', models.CharField(choices=[('public', '公开'), ('private', '私密')], default='public', max_length=10, verbose_name='是否发布')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('introduce', models.CharField(max_length=90, verbose_name='内容简介')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='user.UserProfile', verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'topic',
            },
        ),
    ]
