# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, verbose_name='文章标题'),
        ),
    ]
