# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-08 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('topic', '0002_auto_20200607_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('msg_id', models.IntegerField(null=True, verbose_name='留言定位')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user.UserProfile', verbose_name='作者')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='topic.Topic', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '留言与回复',
                'verbose_name_plural': '留言与回复',
                'db_table': 'message1',
            },
        ),
    ]
