# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-08 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_self', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message1',
            old_name='author',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='message1',
            name='content',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
    ]
